[package]
name = "sellershut"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
activitypub_federation = { version = "0.6.2", features = [
    "axum",
], default-features = false }
anyhow = "1.0.95"
async-graphql = { version = "7.0.15", default-features = false, features = ["playground", "time"] }
async-graphql-axum = "7.0.15"
axum = { version = "0.8.0", features = ["macros", "http2"] }
clap = { version = "4.5.29", features = ["derive"] }
config = { version = "0.15.8", features = ["toml"] }
futures-util = { version = "0.3.31", default-features = false }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
time = "0.3.37"
tokio = { version = "1.43.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }
tonic = "0.12.3"
tower-http = { version = "0.6.2", features = [
    "request-id",
    "timeout",
    "trace",
] }
tracing = "0.1.41"
url = "2.5.4"

[dependencies.sellershut-services]
git = "https://github.com/sellershut/services-lib"
features = ["api", "tracing"]

[dependencies.sellershut-core]
git = "https://github.com/sellershut/sellershut-core"
features = ["rpc-client-categories", "rpc-client-users", "serde", "time"]

[dev-dependencies]
fake = "4.0.0"
reqwest = { version = "0.12.12", default-features = false }
