[package]
name = "sellershut"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1.41"

[dependencies.sellershut-services]
git = "https://github.com/sellershut/services-lib"
features = ["postgres", "tracing"]
