[application]
env = "development"
port = 12210
log-level = "h2=info,tower_http=info,debug"

[misc]
instance-name = "alpha"
hostname = "http://localhost:12210"
users-service = "http://localhost:11304"
categories-service = "http://localhost:11610"
listings-service = "http://localhost:1810"

# vim:ft=toml

