[package]
name = "sellershut-users"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
async-trait.workspace = true
sellershut-core = { workspace = true, features = ["serde", "users"] }
sellershut-svc.workspace = true
sellershut-utilities.workspace = true
serde = { workspace = true, features = ["derive"] }
sqlx = { workspace = true, features = ["time", "uuid"] }
thiserror.workspace = true
time = { workspace = true, features = ["serde"] }
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["serde", "v7"] }
