[package]
name = "sellershut-core"
version = "0.0.0"
edition = "2024"
license.workspace = true
publish = false

[dependencies]
secrecy.workspace = true
serde = { workspace = true, optional = true }
sqlx.workspace = true
time.workspace = true
utoipa = { workspace = true, optional = true }
uuid.workspace = true

[features]
default = []
serde = ["dep:serde", "serde/derive", "secrecy/serde", "uuid/serde"]
utoipa = ["dep:utoipa"]
users = []

