[application]
env = "development"
port = 2210
log-level = "h2=info,debug"

[misc]
hostname = "localhost:2210"
instance-name = "alpha"
otel-endpoint = "http://localhost:4317"
users-endpoint = "http://localhost:1304"

# vim:ft=toml
