[package]
name = "sellershut-svc"
version = "0.0.0"
edition = "2024"
license.workspace = true
publish = false

[dependencies]
sellershut-core = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
sqlx = { workspace = true, optional = true }
url = { workspace = true, features = ["serde"] }

[dev-dependencies]
serde_json.workspace = true
tokio = { workspace = true, features = ["macros"] }

[features]
default = []
postgres = ["dep:sqlx", "sqlx/migrate"]
