on:
  push:
    branches: [master, renovate/**]
  pull_request:
name: docker

# cancel on going checks when new code is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  sellerhut:
    runs-on: ubuntu-latest
    name: sellershut / build
    steps:
      - uses: actions/checkout@v4
      - name: build image
        run: docker build -f crates/sellershut/Dockerfile .

  api-categories:
    runs-on: ubuntu-latest
    name: api-categories / build
    steps:
      - uses: actions/checkout@v4
      - name: build image
        run: docker build -f crates/api-categories/Dockerfile .
